import { Providers } from "./providers";

export const metadata = {
  title: "Lumino | Estudio creativo | Web & Diseño",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
